### PR TITLE
Update the tab+threatmodeling.md file.

### PR DESCRIPTION
**Pull request by zbraiterman**

### CODE REVIEW

**Review by jgadsden — APPROVED** [review]
thanks @zbraiterman for these changes, certainly look good to me

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Sadly I don't in this repo.

**Comment by avidouglen** [comment]
Merged, thanks!

**Comment by zbraiterman** [comment]
Thanks, @avidouglen! :)

**Pull request merged**
